In [24]:
import pandas as pd
import string
import nltk

from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

from sklearn.feature_extraction.text import CountVectorizer

In [25]:

nltk.download("punkt")
nltk.download("punkt_tab")

nltk.download("stopwords")

nltk.download("wordnet")
nltk.download("omw-1.4")

nltk.download("averaged_perceptron_tagger")
nltk.download("averaged_perceptron_tagger_eng")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mohit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

True

In [ ]:
science_lines = [
    "Gravity pulls objects toward each other.",
    "Planets orbit stars because of gravity.",
    "The Earth rotates once every day.",
    "The Moon affects ocean tides.",
    "Stars produce light through nuclear fusion.",
    "Galaxies contain billions of stars.",
    "Telescopes help scientists observe space.",
    "Mars has dust storms and polar ice.",
    "Jupiter is the largest planet.",
    "Saturn has bright rings made of ice.",
    "The Sun provides energy for Earth.",
    "Plants use sunlight for photosynthesis.",
    "Cells are the basic unit of life.",
    "DNA stores genetic information.",
    "Atoms make up all matter.",
    "Electrons move around atomic nuclei.",
    "Water is made of hydrogen and oxygen.",
    "Energy can change forms.",
    "Heat moves from warmer objects to cooler objects.",
    "Sound travels through vibrations.",
    "Light can travel through empty space.",
    "Magnets attract certain metals.",
    "Electricity moves through conductors.",
    "Friction slows moving objects.",
    "Force can change motion.",
    "Mass measures the amount of matter.",
    "Temperature measures how hot something is.",
    "Rocks can form from lava.",
    "Volcanoes release gas and molten rock.",
    "Earthquakes happen when tectonic plates move.",
    "Weather changes from day to day.",
    "Climate describes long term weather patterns.",
    "Clouds form when water vapor cools.",
    "Rain falls from clouds.",
    "Oceans cover most of Earth.",
    "Ecosystems include living and nonliving things.",
    "Animals adapt to their environments.",
    "Bacteria can live in many places.",
    "Viruses need host cells to reproduce.",
    "The brain controls the nervous system.",
    "The heart pumps blood through the body.",
    "Lungs help animals breathe oxygen.",
    "Chemical reactions create new substances.",
    "Scientists test ideas using experiments.",
    "Data helps scientists support conclusions.",
    "Machines can make work easier.",
    "The internet moves information quickly.",
    "Computers process data using instructions.",
    "Artificial intelligence can learn patterns.",
    "Machine learning models find relationships in data."
]

with open("science.txt", "w") as file:
    for line in science_lines:
        file.write(line + "\n")

In [27]:
with open("science.txt", "r") as file:
    raw_text = file.read()

print(raw_text)

Gravity pulls objects toward each other.
Planets orbit stars because of gravity.
The Earth rotates once every day.
The Moon affects ocean tides.
Stars produce light through nuclear fusion.
Galaxies contain billions of stars.
Telescopes help scientists observe space.
Mars has dust storms and polar ice.
Jupiter is the largest planet.
Saturn has bright rings made of ice.
The Sun provides energy for Earth.
Plants use sunlight for photosynthesis.
Cells are the basic unit of life.
DNA stores genetic information.
Atoms make up all matter.
Electrons move around atomic nuclei.
Water is made of hydrogen and oxygen.
Energy can change forms.
Heat moves from warmer objects to cooler objects.
Sound travels through vibrations.
Light can travel through empty space.
Magnets attract certain metals.
Electricity moves through conductors.
Friction slows moving objects.
Force can change motion.
Mass measures the amount of matter.
Temperature measures how hot something is.
Rocks can form from lava.
Volcanoes release gas and molten rock.
Earthquakes happen when tectonic plates move.
Weather changes from day to day.
Climate describes long term weather patterns.
Clouds form when water vapor cools.
Rain falls from clouds.
Oceans cover most of Earth.
Ecosystems include living and nonliving things.
Animals adapt to their environments.
Bacteria can live in many places.
Viruses need host cells to reproduce.
The brain controls the nervous system.
The heart pumps blood through the body.
Lungs help animals breathe oxygen.
Chemical reactions create new substances.
Scientists test ideas using experiments.
Data helps scientists support conclusions.
Machines can make work easier.
The internet moves information quickly.
Computers process data using instructions.
Artificial intelligence can learn patterns.
Machine learning models find relationships in data.

In [28]:
lines = raw_text.splitlines()

df = pd.DataFrame(lines, columns=["original"])

df

                                             original
0            Gravity pulls objects toward each other.
1             Planets orbit stars because of gravity.
2                   The Earth rotates once every day.
3                       The Moon affects ocean tides.
4         Stars produce light through nuclear fusion.
5                 Galaxies contain billions of stars.
6           Telescopes help scientists observe space.
7                 Mars has dust storms and polar ice.
8                      Jupiter is the largest planet.
9                Saturn has bright rings made of ice.
10                 The Sun provides energy for Earth.
11            Plants use sunlight for photosynthesis.
12                  Cells are the basic unit of life.
13                    DNA stores genetic information.
14                          Atoms make up all matter.
15               Electrons move around atomic nuclei.
16              Water is made of hydrogen and oxygen.
17                           Energy can change forms.
18  Heat moves from warmer objects to cooler objects.
19                  Sound travels through vibrations.
20              Light can travel through empty space.
21                    Magnets attract certain metals.
22              Electricity moves through conductors.
23                     Friction slows moving objects.
24                           Force can change motion.
25                Mass measures the amount of matter.
26         Temperature measures how hot something is.
27                          Rocks can form from lava.
28             Volcanoes release gas and molten rock.
29      Earthquakes happen when tectonic plates move.
30                   Weather changes from day to day.
31      Climate describes long term weather patterns.
32                Clouds form when water vapor cools.
33                            Rain falls from clouds.
34                        Oceans cover most of Earth.
35    Ecosystems include living and nonliving things.
36               Animals adapt to their environments.
37                  Bacteria can live in many places.
38              Viruses need host cells to reproduce.
39             The brain controls the nervous system.
40            The heart pumps blood through the body.
41                 Lungs help animals breathe oxygen.
42          Chemical reactions create new substances.
43           Scientists test ideas using experiments.
44         Data helps scientists support conclusions.
45                     Machines can make work easier.
46            The internet moves information quickly.
47         Computers process data using instructions.
48        Artificial intelligence can learn patterns.
49  Machine learning models find relationships in ...

In [29]:
def get_wordnet_pos(tag):

    if tag.startswith("J"):
        return wordnet.ADJ

    elif tag.startswith("V"):
        return wordnet.VERB

    elif tag.startswith("N"):
        return wordnet.NOUN

    elif tag.startswith("R"):
        return wordnet.ADV

    else:
        return wordnet.NOUN

In [30]:
def preprocess(text):

    # tokenize
    tokens = word_tokenize(text)

    # lowercase
    tokens = [word.lower() for word in tokens]

    # remove punctuation
    tokens = [
        word for word in tokens
        if word not in string.punctuation
    ]

    # remove stopwords
    stop_words = set(stopwords.words("english"))

    tokens = [
        word for word in tokens
        if word not in stop_words
    ]

    # pos tagging
    tagged_tokens = pos_tag(tokens)

    # lemmatize
    lemmatizer = WordNetLemmatizer()

    cleaned_tokens = [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged_tokens
    ]

    return " ".join(cleaned_tokens)

In [31]:
df["cleaned"] = df["original"].apply(preprocess)

pd.set_option("display.max_colwidth", None)

df

,original,cleaned
0,Gravity pulls objects toward each other.,gravity pull object toward
1,Planets orbit stars because of gravity.,planet orbit star gravity
2,The Earth rotates once every day.,earth rotates every day
3,The Moon affects ocean tides.,moon affect ocean tide
4,Stars produce light through nuclear fusion.,star produce light nuclear fusion
5,Galaxies contain billions of stars.,galaxy contain billion star
6,Telescopes help scientists observe space.,telescope help scientist observe space
7,Mars has dust storms and polar ice.,mar dust storm polar ice
8,Jupiter is the largest planet.,jupiter large planet
9,Saturn has bright rings made of ice.,saturn bright ring make ice
10,The Sun provides energy for Earth.,sun provide energy earth
11,Plants use sunlight for photosynthesis.,plant use sunlight photosynthesis
12,Cells are the basic unit of life.,cell basic unit life
13,DNA stores genetic information.,dna store genetic information
14,Atoms make up all matter.,atom make matter
15,Electrons move around atomic nuclei.,electron move around atomic nucleus
16,Water is made of hydrogen and oxygen.,water make hydrogen oxygen
17,Energy can change forms.,energy change form
18,Heat moves from warmer objects to cooler objects.,heat move warmer object cool object
19,Sound travels through vibrations.,sound travel vibration
20,Light can travel through empty space.,light travel empty space
21,Magnets attract certain metals.,magnet attract certain metal
22,Electricity moves through conductors.,electricity move conductor
23,Friction slows moving objects.,friction slow move object
24,Force can change motion.,force change motion
25,Mass measures the amount of matter.,mass measure amount matter
26,Temperature measures how hot something is.,temperature measure hot something
27,Rocks can form from lava.,rock form lava
28,Volcanoes release gas and molten rock.,volcano release gas molten rock
29,Earthquakes happen when tectonic plates move.,earthquake happen tectonic plate move
30,Weather changes from day to day.,weather change day day
31,Climate describes long term weather patterns.,climate describes long term weather pattern
32,Clouds form when water vapor cools.,cloud form water vapor cool
33,Rain falls from clouds.,rain fall cloud
34,Oceans cover most of Earth.,ocean cover earth
35,Ecosystems include living and nonliving things.,ecosystem include live nonliving thing
36,Animals adapt to their environments.,animal adapt environment
37,Bacteria can live in many places.,bacteria live many place
38,Viruses need host cells to reproduce.,virus need host cell reproduce
39,The brain controls the nervous system.,brain control nervous system
40,The heart pumps blood through the body.,heart pump blood body
41,Lungs help animals breathe oxygen.,lung help animal breathe oxygen
42,Chemical reactions create new substances.,chemical reaction create new substance
43,Scientists test ideas using experiments.,scientist test idea use experiment
44,Data helps scientists support conclusions.,data help scientist support conclusion
45,Machines can make work easier.,machine make work easier
46,The internet moves information quickly.,internet move information quickly
47,Computers process data using instructions.,computer process data use instruction
48,Artificial intelligence can learn patterns.,artificial intelligence learn pattern
49,Machine learning models find relationships in data.,machine learn model find relationship data

In [32]:
vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(df["cleaned"])

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df

,adapt,affect,amount,animal,around,artificial,atom,atomic,attract,bacteria,...,unit,use,vapor,vibration,virus,volcano,warmer,water,weather,work
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
48,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
word_counts = bow_df.sum().sort_values(ascending=False)

word_counts.head(10)

move      6
make      4
object    4
data      3
change    3
form      3
help      3
day       3
earth     3
star      3
dtype: int64

# Reflection

Preprocessing changed the text by converting words to lowercase, removing punctuation, removing stopwords, and lemmatizing words into base forms. Most common words from Bag of Words output were data, earth, object, scientist, and energy. Bag of Words is useful because it converts text into numbers that a model can analyze.